// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: LDC_SLAVE

#include "../ui.h"

void ui_get_start_scr_init(void)
{
    get_start_scr = lv_obj_create(NULL);
    lv_obj_clear_flag(get_start_scr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(get_start_scr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(get_start_scr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    get_start_text = lv_label_create(get_start_scr);
    lv_obj_set_width(get_start_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(get_start_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(get_start_text, -7);
    lv_obj_set_y(get_start_text, -86);
    lv_obj_set_align(get_start_text, LV_ALIGN_CENTER);
    lv_label_set_text(get_start_text, "Get start");
    lv_obj_set_style_text_color(get_start_text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(get_start_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(get_start_text, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(get_start_scr);
    lv_obj_set_width(ui_Panel1, 292);
    lv_obj_set_height(ui_Panel1, 96);
    lv_obj_set_x(ui_Panel1, -1);
    lv_obj_set_y(ui_Panel1, -3);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Panel1, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ssid_text = lv_label_create(get_start_scr);
    lv_obj_set_width(ssid_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ssid_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ssid_text, -112);
    lv_obj_set_y(ssid_text, -29);
    lv_obj_set_align(ssid_text, LV_ALIGN_CENTER);
    lv_label_set_text(ssid_text, "SSID");
    lv_obj_set_style_text_color(ssid_text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ssid_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ssid_text, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ssid_text_area = lv_textarea_create(get_start_scr);
    lv_obj_set_width(ssid_text_area, 268);
    lv_obj_set_height(ssid_text_area, 34);
    lv_obj_set_x(ssid_text_area, 0);
    lv_obj_set_y(ssid_text_area, 8);
    lv_obj_set_align(ssid_text_area, LV_ALIGN_CENTER);
    lv_textarea_set_text(ssid_text_area, "SSID");
    lv_textarea_set_placeholder_text(ssid_text_area, "SSID");
    lv_obj_set_style_text_font(ssid_text_area, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(get_start_scr);
    lv_obj_set_width(ui_Panel2, 147);
    lv_obj_set_height(ui_Panel2, 32);
    lv_obj_set_x(ui_Panel2, -8);
    lv_obj_set_y(ui_Panel2, 80);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Panel2, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_submit_setting_btn = lv_btn_create(get_start_scr);
    lv_obj_set_width(ui_submit_setting_btn, 147);
    lv_obj_set_height(ui_submit_setting_btn, 32);
    lv_obj_set_x(ui_submit_setting_btn, -8);
    lv_obj_set_y(ui_submit_setting_btn, 80);
    lv_obj_set_align(ui_submit_setting_btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_submit_setting_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_submit_setting_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_submit_setting_btn, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_submit_setting_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_submit_setting_btn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_submit_setting_btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_submit_setting_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_submit_setting_btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_submit_setting_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    submit_btn_t = lv_label_create(ui_submit_setting_btn);
    lv_label_set_text(submit_btn_t,"Submit");
    lv_obj_set_style_text_font(submit_btn_t, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_center(submit_btn_t);

    //lv_obj_add_event_cb(ui_submit_setting_btn, event_submit_btn, LV_EVENT_ALL, NULL);

}