// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: LDC_SLAVE

#include "../ui.h"

void ui_Screen_init(void)
{
    ui_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp_t = lv_label_create(ui_Screen);
    lv_obj_set_width(ui_temp_t, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp_t, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp_t, 12);
    lv_obj_set_y(ui_temp_t, -40);
    lv_obj_set_align(ui_temp_t, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp_t, "0.0");
    lv_obj_set_style_text_color(ui_temp_t, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp_t, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temp_t, &ui_font_Font118, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart1 = lv_chart_create(ui_Screen);
    lv_obj_set_width(ui_Chart1, 300);
    lv_obj_set_height(ui_Chart1, 60);
    lv_obj_set_x(ui_Chart1, 0);
    lv_obj_set_y(ui_Chart1, 70);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, -20, 40);
    lv_chart_set_update_mode(ui_Chart1, LV_CHART_UPDATE_MODE_SHIFT);
    lv_chart_set_div_line_count(ui_Chart1, 20, 20);
    lv_obj_set_style_bg_color(ui_Chart1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Chart1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Chart1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Chart1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_Chart1, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Chart1, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_Chart1, lv_color_hex(0x00FFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Chart1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_Chart1, lv_color_hex(0x4040FF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart1, 0, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Chart1, lv_color_hex(0x808080), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chart1, 0, LV_PART_TICKS | LV_STATE_DEFAULT);


    ui_dev_name_t = lv_label_create(ui_Screen);
    lv_obj_set_width(ui_dev_name_t, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dev_name_t, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dev_name_t, -104);
    lv_obj_set_y(ui_dev_name_t, -96);
    lv_obj_set_align(ui_dev_name_t, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dev_name_t, "Device 1");
    lv_obj_set_style_text_color(ui_dev_name_t, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dev_name_t, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dev_name_t, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_c_text = lv_label_create(ui_Screen);
    lv_obj_set_width(ui_c_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_c_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_c_text, 134);
    lv_obj_set_y(ui_c_text, -56);
    lv_obj_set_align(ui_c_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_c_text, "C");
    lv_obj_set_style_text_color(ui_c_text, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_c_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_c_text, &ui_font_Font72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bar = lv_bar_create(ui_Screen);
    lv_bar_set_start_value(ui_bar, -20, LV_ANIM_OFF);
    lv_obj_set_width(ui_bar, 214);
    lv_obj_set_height(ui_bar, 10);
    lv_obj_set_x(ui_bar, -27);
    lv_obj_set_y(ui_bar, 18);
    lv_obj_set_align(ui_bar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_bar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bar, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_bar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_bar, lv_color_hex(0x00FFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_symbol_c = lv_label_create(ui_Screen);
    lv_obj_set_width(ui_symbol_c, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_symbol_c, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_symbol_c, 110);
    lv_obj_set_y(ui_symbol_c, -75);
    lv_obj_set_align(ui_symbol_c, LV_ALIGN_CENTER);
    lv_label_set_text(ui_symbol_c, "o");
    lv_obj_set_style_text_color(ui_symbol_c, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_symbol_c, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_symbol_c, &ui_font_Font32, LV_PART_MAIN | LV_STATE_DEFAULT);

}