// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

<<<<<<< HEAD
//Get start screen
void ui_get_start_scr_init(void);
lv_obj_t * get_start_scr;
lv_obj_t * get_start_text;
lv_obj_t * ui_Panel1;
lv_obj_t * ssid_text;
lv_obj_t * ssid_text_area;
lv_obj_t * ui_Panel2;
lv_obj_t * submit_btn_t;
lv_obj_t * ui_submit_setting_btn;

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen;
lv_obj_t * ui_dev_name_t;
lv_obj_t * ui_Chart1;
lv_obj_t * ui_temp_t;
lv_obj_t * ui_c_text;
lv_obj_t * ui_chart_text;
lv_obj_t * ui_bar;
lv_obj_t * ui_symbol_c;
lv_obj_t * ui_symbol_c;
lv_obj_t * ui____initial_actions0;
void event_submit_btn(lv_event_t *e);
=======

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_CardMini1;
lv_obj_t * ui_Arc1;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Chart1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;
lv_obj_t * ui____initial_actions0;
>>>>>>> de6793528c1a5617cd571390f88dff0579b7874f
// lv_chart_series_t * ui_Chart1_series_1;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
<<<<<<< HEAD
void event_submit_btn(lv_event_t *e){
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED){
        lv_scr_load(ui_Screen);
    }
}
=======

>>>>>>> de6793528c1a5617cd571390f88dff0579b7874f
///////////////////// SCREENS ////////////////////

void ui_init(void)
{
<<<<<<< HEAD
    ui_Screen_init();
    // ui_get_start_scr_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    // lv_disp_load_scr(get_start_scr);
     lv_disp_load_scr(ui_Screen);
=======
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
>>>>>>> de6793528c1a5617cd571390f88dff0579b7874f
}
