// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"
<<<<<<< HEAD

LV_FONT_DECLARE(ui_font_Digital16);
LV_FONT_DECLARE(ui_font_digitfont42);
LV_FONT_DECLARE(ui_font_Font16);
LV_FONT_DECLARE(ui_font_Font32);
LV_FONT_DECLARE(ui_font_Font72);
LV_FONT_DECLARE(ui_font_Font108);
LV_FONT_DECLARE(ui_font_Font118);

void ui_get_start_scr_init(void);
extern lv_obj_t * get_start_scr;
extern lv_obj_t * get_start_text;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ssid_text;
extern lv_obj_t * ssid_text_area;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * submit_btn_t;
extern lv_obj_t * ui_submit_setting_btn;

// SCREEN: ui_Screen1
void ui_Screen_init(void);
extern lv_obj_t * ui_Screen;
extern lv_obj_t * ui_dev_name_t;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_temp_t;
extern lv_obj_t * ui_c_text;
extern lv_obj_t * ui_bar;
extern lv_obj_t * ui_symbol_c;
extern lv_obj_t * ui_kb;
extern lv_obj_t * ui____initial_actions0;
// void event_submit_btn(lv_event_t *e);
=======
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_CardMini1;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui____initial_actions0;
// extern lv_chart_series_t * ui_Chart1_series_1;
>>>>>>> de6793528c1a5617cd571390f88dff0579b7874f

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
